const mockCourses = [
    {
        logo: 'GeekBrains',
        courseCategory: 'Programación Web',
        courseImage: 'CourseImg1',
        title: 'Utilización de Metatags',
        hours: '12',
        slots: '30',
        rating: '5',
        discountTag: '-68%',
        extraTags: ['Capacitación en MD'],
        originalPrice: '11 426',
        discountedPrice: '3 550',
        installmentPrice: '127',
        installmentPeriod: '10'
    },
    {
        logo: 'Skillbox',
        courseCategory: 'Programación Web',
        courseImage: 'CourseImg2',
        title: 'Testing manual con Cypress',
        hours: '6',
        slots: '30',
        rating: '4',
        discountTag: '-56%',
        extraTags: [],
        originalPrice: '11 426',
        discountedPrice: '3 550',
        installmentPrice: '127',
        installmentPeriod: '5'
    },
    {
        logo: 'SkillFactory',
        courseCategory: 'Experto en Data Science',
        courseImage: 'CourseImg3',
        title: 'Introducción a Data Scientist',
        hours: '24',
        slots: '27',
        rating: '4.5',
        discountTag: '-44%',
        extraTags: ['En vivo'],
        originalPrice: '6 350',
        discountedPrice: '3 550',
        installmentPrice: '174',
        installmentPeriod: '10'
    },
    {
        logo: 'Skillbox',
        courseCategory: 'Programación Web',
        courseImage: 'CourseImg2',
        title: 'Testing Unitario',
        hours: '5',
        slots: '50',
        rating: '3.5',
        discountTag: '-57%',
        extraTags: ['Free with subscription'],
        originalPrice: '11 426',
        discountedPrice: '3 550',
        installmentPrice: '149',
        installmentPeriod: '5'
    },
    {
        logo: 'School',
        courseCategory: 'Testing Autónomo',
        courseImage: 'CourseImg3',
        title: 'Testing Manual con SoapUI',
        hours: '6',
        slots: '30',
        rating: '4.5',
        discountTag: '-52%',
        extraTags: ['Compensación posible'],
        originalPrice: '11 426',
        discountedPrice: '3 550',
        installmentPrice: '55',
        installmentPeriod: '5'
    },
    {
        logo: 'GeekBrains',
        courseCategory: 'Marketing',
        courseImage: 'CourseImg1',
        title: 'Digital-Marketing Inicial',
        hours: '10',
        slots: '30',
        rating: '4',
        discountTag: '-70%',
        extraTags: [],
        originalPrice: '11 426',
        discountedPrice: '3 550',
        installmentPrice: '89',
        installmentPeriod: '5'
    }
];

export default mockCourses;
